/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum log_type {
	INFO = 1,
	WARN = 2,
	ERROR = 3,
};
typedef enum log_type log_type;

struct message {
	char logMsg[1024];
	log_type type;
	char *timestamp;
};
typedef struct message message;

struct ServerResponse {
	int ack;
	char *errorMsg;
};
typedef struct ServerResponse ServerResponse;

struct LogRequest {
	log_type type;
};
typedef struct LogRequest LogRequest;

struct LogResponse {
	struct {
		u_int logs_len;
		message *logs_val;
	} logs;
};
typedef struct LogResponse LogResponse;

#define LOG_PROG 0x2000001
#define LOG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sendMessageToServer 1
extern  ServerResponse * sendmessagetoserver_1(message *, CLIENT *);
extern  ServerResponse * sendmessagetoserver_1_svc(message *, struct svc_req *);
#define getLogs 2
extern  LogResponse * getlogs_1(LogRequest *, CLIENT *);
extern  LogResponse * getlogs_1_svc(LogRequest *, struct svc_req *);
extern int log_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sendMessageToServer 1
extern  ServerResponse * sendmessagetoserver_1();
extern  ServerResponse * sendmessagetoserver_1_svc();
#define getLogs 2
extern  LogResponse * getlogs_1();
extern  LogResponse * getlogs_1_svc();
extern int log_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_type (XDR *, log_type*);
extern  bool_t xdr_message (XDR *, message*);
extern  bool_t xdr_ServerResponse (XDR *, ServerResponse*);
extern  bool_t xdr_LogRequest (XDR *, LogRequest*);
extern  bool_t xdr_LogResponse (XDR *, LogResponse*);

#else /* K&R C */
extern bool_t xdr_log_type ();
extern bool_t xdr_message ();
extern bool_t xdr_ServerResponse ();
extern bool_t xdr_LogRequest ();
extern bool_t xdr_LogResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
