/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "main.h"

bool_t
xdr_log_type (XDR *xdrs, log_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->logMsg, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_log_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->timestamp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ServerResponse (XDR *xdrs, ServerResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ack))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->errorMsg, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LogRequest (XDR *xdrs, LogRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_log_type (xdrs, &objp->type))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LogResponse (XDR *xdrs, LogResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->logs.logs_val, (u_int *) &objp->logs.logs_len, ~0,
		sizeof (message), (xdrproc_t) xdr_message))
		 return FALSE;
	return TRUE;
}
