/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "main.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

ServerResponse *
sendmessagetoserver_1(message *argp, CLIENT *clnt)
{
	static ServerResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, sendMessageToServer,
		(xdrproc_t) xdr_message, (caddr_t) argp,
		(xdrproc_t) xdr_ServerResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

LogResponse *
getlogs_1(LogRequest *argp, CLIENT *clnt)
{
	static LogResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, getLogs,
		(xdrproc_t) xdr_LogRequest, (caddr_t) argp,
		(xdrproc_t) xdr_LogResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
