/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
};
typedef struct numbers numbers;

#define CALC_PROG 0x1234567
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  double * add_1(numbers *, CLIENT *);
extern  double * add_1_svc(numbers *, struct svc_req *);
#define sub 2
extern  double * sub_1(numbers *, CLIENT *);
extern  double * sub_1_svc(numbers *, struct svc_req *);
#define multiply 3
extern  double * multiply_1(numbers *, CLIENT *);
extern  double * multiply_1_svc(numbers *, struct svc_req *);
#define divide 4
extern  double * divide_1(numbers *, CLIENT *);
extern  double * divide_1_svc(numbers *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  double * add_1();
extern  double * add_1_svc();
#define sub 2
extern  double * sub_1();
extern  double * sub_1_svc();
#define multiply 3
extern  double * multiply_1();
extern  double * multiply_1_svc();
#define divide 4
extern  double * divide_1();
extern  double * divide_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
