/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ArrayData {
	int arraySize;
	int array[100];
};
typedef struct ArrayData ArrayData;

#define AVG_PROG 0x4562877
#define AVG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define calAvg 1
extern  int * calavg_1(ArrayData *, CLIENT *);
extern  int * calavg_1_svc(ArrayData *, struct svc_req *);
extern int avg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calAvg 1
extern  int * calavg_1();
extern  int * calavg_1_svc();
extern int avg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ArrayData (XDR *, ArrayData*);

#else /* K&R C */
extern bool_t xdr_ArrayData ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
