/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"
#include "stdio.h"

void
avg_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	ArrayData  calavg_1_arg;

	printf("Enter the size of the array : ");
	scanf("%d",&calavg_1_arg.arraySize);

	if( calavg_1_arg.arraySize > 100 ){

		printf("ArraySize over 100 not allowed\n");
		return;
	}

	printf("ENter %d integers",calavg_1_arg.arraySize);
	for( int i = 0 ; i < calavg_1_arg.arraySize ; i++){
		scanf("%d",&calavg_1_arg.array[i]);
	}

	


#ifndef	DEBUG
	clnt = clnt_create (host, AVG_PROG, AVG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calavg_1(&calavg_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}


	printf("avg value is : %d\n",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	avg_prog_1 (host);
exit (0);
}
