/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"

int *
calavg_1_svc(ArrayData *argp, struct svc_req *rqstp)
{
	static int  result;
	
	int sum = 0;
	for( int i = 0;  i < argp->arraySize ; i++ )
	{
		sum += argp->array[i];
	}

	result = sum / argp->arraySize;
	/*
	 * insert server code here
	 */
	printf("Server side work done , answer is %d\n",result);
	return &result;
}
