/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum TaskType {
	CREATE_FILE = 1,
	READ_FILE = 2,
	DELETE_FILE = 3,
};
typedef enum TaskType TaskType;

enum StatusCode {
	OP_SUCCESS = 0,
	FILE_NOT_FOUND = 1,
	PERMISSION_DENIED = 2,
	UNKNOWN_ERROR = 3,
};
typedef enum StatusCode StatusCode;

struct FileOperation {
	int task;
	int status;
	char filename[1024];
	char content[1024];
};
typedef struct FileOperation FileOperation;

#define CRUD_PROG 0x2000001
#define CRUD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define createFile 1
extern  FileOperation * createfile_1(FileOperation *, CLIENT *);
extern  FileOperation * createfile_1_svc(FileOperation *, struct svc_req *);
#define readFile 2
extern  FileOperation * readfile_1(FileOperation *, CLIENT *);
extern  FileOperation * readfile_1_svc(FileOperation *, struct svc_req *);
#define deleteFile 3
extern  FileOperation * deletefile_1(FileOperation *, CLIENT *);
extern  FileOperation * deletefile_1_svc(FileOperation *, struct svc_req *);
extern int crud_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define createFile 1
extern  FileOperation * createfile_1();
extern  FileOperation * createfile_1_svc();
#define readFile 2
extern  FileOperation * readfile_1();
extern  FileOperation * readfile_1_svc();
#define deleteFile 3
extern  FileOperation * deletefile_1();
extern  FileOperation * deletefile_1_svc();
extern int crud_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_TaskType (XDR *, TaskType*);
extern  bool_t xdr_StatusCode (XDR *, StatusCode*);
extern  bool_t xdr_FileOperation (XDR *, FileOperation*);

#else /* K&R C */
extern bool_t xdr_TaskType ();
extern bool_t xdr_StatusCode ();
extern bool_t xdr_FileOperation ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
