/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "main.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

FileOperation *
createfile_1(FileOperation *argp, CLIENT *clnt)
{
	static FileOperation clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, createFile,
		(xdrproc_t) xdr_FileOperation, (caddr_t) argp,
		(xdrproc_t) xdr_FileOperation, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

FileOperation *
readfile_1(FileOperation *argp, CLIENT *clnt)
{
	static FileOperation clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, readFile,
		(xdrproc_t) xdr_FileOperation, (caddr_t) argp,
		(xdrproc_t) xdr_FileOperation, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

FileOperation *
deletefile_1(FileOperation *argp, CLIENT *clnt)
{
	static FileOperation clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, deleteFile,
		(xdrproc_t) xdr_FileOperation, (caddr_t) argp,
		(xdrproc_t) xdr_FileOperation, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
