/*
 * This is sample code generated by rpcgen.
 * Modified to handle file operations based on user input.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "main.h"

void crud_prog_1(char *host, int operation, char *filename, char *content) {
    CLIENT *clnt;
    FileOperation *result;
    FileOperation op_arg;

    /* Initialize the request structure */
    memset(&op_arg, 0, sizeof(op_arg));
    op_arg.task = operation;
    strncpy(op_arg.filename, filename, 1024);

    if (operation == CREATE_FILE && content != NULL) {
        strncpy(op_arg.content, content, 1024);
    }

    /* Create client */
#ifndef DEBUG
    clnt = clnt_create(host, CRUD_PROG, CRUD_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    /* Perform the requested operation */
    switch (operation) {
        case CREATE_FILE:
            result = createfile_1(&op_arg, clnt);
            break;
        case READ_FILE:
            result = readfile_1(&op_arg, clnt);
            break;
        case DELETE_FILE:
            result = deletefile_1(&op_arg, clnt);
            break;
        default:
            printf("Invalid operation.\n");
            exit(1);
    }

    /* Check for RPC call failure */
    if (result == (FileOperation *)NULL) {
        clnt_perror(clnt, "RPC call failed");
        exit(1);
    }

    /* Process the result */
    if (result->status == OP_SUCCESS) {
        if (operation == READ_FILE) {
            printf("File Contents:\n%s\n", result->content);
        } else {
            printf("Operation successful.\n");
        }
    } else {
        printf("Operation failed with status code: %d\n", result->status);
    }

#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
    if (argc < 3) {
        printf("Usage: %s <server_host> <operation> <filename> [content]\n", argv[0]);
        printf("Operations: create, read, delete\n");
        exit(1);
    }

    char *host = argv[1];
    int operation;

    if (strcmp(argv[2], "create") == 0 && argc == 5) {
        operation = CREATE_FILE;
    } else if (strcmp(argv[2], "read") == 0 && argc == 4) {
        operation = READ_FILE;
    } else if (strcmp(argv[2], "delete") == 0 && argc == 4) {
        operation = DELETE_FILE;
    } else {
        printf("Invalid command. Use:\n");
        printf("  %s <server_host> create <filename> <content>\n", argv[0]);
        printf("  %s <server_host> read <filename>\n", argv[0]);
        printf("  %s <server_host> delete <filename>\n", argv[0]);
        exit(1);
    }

    crud_prog_1(host, operation, argv[3], argc == 5 ? argv[4] : NULL);
    return 0;
}
