/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "main.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

AuthResponse *
send_credentials_1(Credentials *argp, CLIENT *clnt)
{
	static AuthResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, send_credentials,
		(xdrproc_t) xdr_Credentials, (caddr_t) argp,
		(xdrproc_t) xdr_AuthResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
