/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Credentials {
	int action;
	char username[1024];
	char password[1024];
};
typedef struct Credentials Credentials;

struct AuthResponse {
	int status;
	char message[1024];
};
typedef struct AuthResponse AuthResponse;

#define AUTH_PROG 0x2000001
#define AUTH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_credentials 1
extern  AuthResponse * send_credentials_1(Credentials *, CLIENT *);
extern  AuthResponse * send_credentials_1_svc(Credentials *, struct svc_req *);
extern int auth_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_credentials 1
extern  AuthResponse * send_credentials_1();
extern  AuthResponse * send_credentials_1_svc();
extern int auth_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Credentials (XDR *, Credentials*);
extern  bool_t xdr_AuthResponse (XDR *, AuthResponse*);

#else /* K&R C */
extern bool_t xdr_Credentials ();
extern bool_t xdr_AuthResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
