/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "main.h"

bool_t
xdr_Message (XDR *xdrs, Message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->sender, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->content, 500))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MessageQueue (XDR *xdrs, MessageQueue *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->MessageQueue_val, (u_int *) &objp->MessageQueue_len, 100,
		sizeof (Message), (xdrproc_t) xdr_Message))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MessageQueue (XDR *xdrs, MessageQueue *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->messages, 100,
		sizeof (Message), (xdrproc_t) xdr_Message))
		 return FALSE;
	return TRUE;
}
