/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Message {
	char *sender;
	char *content;
};
typedef struct Message Message;

typedef struct {
	u_int MessageQueue_len;
	Message *MessageQueue_val;
} MessageQueue;

struct MessageQueue {
	Message messages[100];
};
typedef struct MessageQueue MessageQueue;

#define CHAT_PROG 0x20000001
#define CHAT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SEND_MESSAGE 1
extern  void * send_message_1(Message *, CLIENT *);
extern  void * send_message_1_svc(Message *, struct svc_req *);
#define GET_MESSAGES 2
extern  MessageQueue * get_messages_1(void *, CLIENT *);
extern  MessageQueue * get_messages_1_svc(void *, struct svc_req *);
extern int chat_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SEND_MESSAGE 1
extern  void * send_message_1();
extern  void * send_message_1_svc();
#define GET_MESSAGES 2
extern  MessageQueue * get_messages_1();
extern  MessageQueue * get_messages_1_svc();
extern int chat_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Message (XDR *, Message*);
extern  bool_t xdr_MessageQueue (XDR *, MessageQueue*);
extern  bool_t xdr_MessageQueue (XDR *, MessageQueue*);

#else /* K&R C */
extern bool_t xdr_Message ();
extern bool_t xdr_MessageQueue ();
extern bool_t xdr_MessageQueue ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
