/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"

int *add_1_svc(argp)
	numbers *argp;
{

	static int  result;

	/*
	 * insert server code here
	 */
	 printf("a = %d , b = %d\n",argp->a,argp->b);
	 result = argp->a + argp->b;

	return(&result);
}
